### ISSUE TITLE
undefined reference to 'bsd_signal' when trying to build against NDK 11

### ISSUE THREAD

**Issue by ghost** [gcesarmza/curl-android-ios#12]
Hello, After upgrade to latest NDK 11 I see following linking error, probably libcurl rebuild is required to fix that issue

/Users/rd/mobile-framework/sandbox/curl-prebuilt-with-ssl/android/armeabi-v7a/libcurl.a(ui_openssl.o):function read_string_inner: error: undefined reference to 'bsd_signal'
/Users/rd/Library/Android/sdk/ndk-bundle/platforms/android-3/arch-arm/usr/include/signal.h
Error:(111) undefined reference to 'bsd_signal'
Error:error: ld returned 1 exit status

**Comment by gustavogenovese** [comment]
Cant reproduce this
