### ISSUE TITLE
zlib symbols are missing

### ISSUE THREAD

**Issue by ogoren** [gcesarmza/curl-android-ios#13]
Hey.
When trying to link the libCurl library with my code, I get many zlib linkage errors. What should I do?

C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(version.o): in function curl_version:(.text.curl_version+0x5e): error: undefined reference to 'zlibVersion'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(version.o): in function curl_version_info:(.text.curl_version_info+0x1a): error: undefined reference to 'zlibVersion'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function Curl_unencode_deflate_write:(.text.Curl_unencode_deflate_write+0x3a): error: undefined reference to 'inflateInit_'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0x58): error: undefined reference to 'inflate'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0x9c): error: undefined reference to 'inflateEnd'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0xaa): error: undefined reference to 'inflateInit2_'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0xba): error: undefined reference to 'inflateEnd'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0xe8): error: undefined reference to 'inflateEnd'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function inflate_stream:(.text.inflate_stream+0xfa): error: undefined reference to 'inflateEnd'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function Curl_unencode_gzip_write:(.text.Curl_unencode_gzip_write+0x54): error: undefined reference to 'zlibVersion'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function Curl_unencode_gzip_write:(.text.Curl_unencode_gzip_write+0x70): error: undefined reference to 'inflateInit2_'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(content_encoding.o): in function Curl_unencode_gzip_write:(.text.Curl_unencode_gzip_write+0x13a): error: undefined reference to 'inflateInit2_'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(curl_ntlm_wb.o): in function Curl_output_ntlm_wb:(.text.Curl_output_ntlm_wb+0x21e): error: undefined reference to 'getpwuid_r'
C:/Android/android-ndk-r10/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/svn_wc/beehd_hypertech/VoipEngine/../ThirdParties/android/lib/libcurl.a(netrc.o): in function Curl_parsenetrc:(.text.Curl_parsenetrc+0x68): error: undefined reference to 'getpwuid_r'
collect2: ld returned 1 exit status

**Comment by ghost** [comment]
try add -lz to LOCAL_LDLIBS in Android.mk
