### ISSUE TITLE
iOS: "We can't compile without socket() support!"

### ISSUE THREAD

**Issue by chuckhacker** [gcesarmza/curl-android-ios#19]
Cannot compile on iOS using build_iOS.sh because:

```
  CC       libcurl_la-ldap.lo
url.c:55:2: error: "We can't compile without socket() support!"
#error "We can't compile without socket() support!"
```

I don't really need ldap any how -- just barebones HTTP/HTTPS support.

**Comment by gustavogenovese** [comment]
Follow the instructions.
`xcode-select --install`

**Comment by chuckhacker** [comment]
Fixed it, thanks for the instructions (I mistakenly thought I had already done that)!
