### ISSUE TITLE
Curl 7.53 support

### ISSUE THREAD

**Issue by johanlantz** [gcesarmza/curl-android-ios#22]
Hi and thanks for your efforts on this one. It has been working really well with the Curl 7.48 version.

Today however I wanted to update to 7.50.3 and ran into some issues. It seems some c files has to be removed from the .mk but even after that I got duplicate definition problems.

If you have the time to see if we the script can support the latest version of curl it would be great.

**Comment by olegazyx** [comment]
+1
Please, update openssl too.

**Comment by gustavogenovese** [comment]
The lib has been updated to 7.50.3

**Comment by johanlantz** [comment]
Thanks Gustavo, much appreciated.

Will give it a go later this week.

Best Regards

Johan

2016-10-31 2:20 GMT+01:00 Gustavo Genovese notifications@github.com:
