### ISSUE TITLE
how to merge multiple libcurl.a into single static library

### ISSUE THREAD

**Issue by ibaoger** [gcesarmza/curl-android-ios#24]
how to merge follow libcurl.a file to only one libcurl.a file?
armeabi/libcurl.a
armeabi-v7a/libcurl.a
...

**Comment by gustavogenovese** [comment]
The .a files must be split in separate directories. You could, though, omit some of them (armeabi will work on v7a and in arm64; mips will work on mips64, x86 will work on x86_64) if you want to use less space.

**Comment by ibaoger** [comment]
OK, thanks.
