### ISSUE TITLE
Can I use this library in C?

### ISSUE THREAD

**Issue by winster** [gcesarmza/curl-android-ios#34]
Hello,

I am building a cross platform SDK in C (common for Android/iOS/Windows) in which I want to use curl. Can I use your library?

Regards
Winster

**Comment by gustavogenovese** [comment]
Yes you can. You'll have to compile cURL for Windows

**Comment by winster** [comment]
Getting an error like this after adding libcurl.a in the project. Anything went wrong?

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lcurl
