### ISSUE TITLE
build for Android fails

### ISSUE THREAD

**Issue by winster** [gcesarmza/curl-android-ios#35]
I was initially getting an error openssl/opensslconf.h was not found. So I created a symlink from /user/local/opt/openssl/include/openssl to /usr/local/incude

But now, getting many other errors. What went wrong?

----------------------------------------------------------------------------------------

Configuring for android

PERL          =perl
PERLVERSION   =5.18.2 for darwin-thread-multi-2level
HASHBANGPERL  =/usr/bin/env perl
CC            =arm-linux-androideabi-gcc
CFLAG         =-Wall -O3 -pthread -mandroid -fPIC --sysroot=$(CROSS_SYSROOT) -Wa,--noexecstack 
CXX           =g++
CXXFLAG       =-Wall -O3 -pthread -mandroid -fPIC --sysroot=$(CROSS_SYSROOT) -Wa,--noexecstack 
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_DYNAMIC_ENGINE OPENSSL_PIC
EX_LIBS       =-ldl 
make: *** No rule to make target `jni/../../openssl/ssl/d1_both.c', needed by `obj/local/arm64-v8a/objs/ssl/__/__/openssl/ssl/d1_both.o'.  Stop.
make: *** Waiting for unfinished jobs....
[arm64-v8a] Compile        : ssl <= bio_ssl.c
In file included from jni/../../openssl/ssl/bio_ssl.c:15:
In file included from jni/../../openssl/include/internal/bio.h:10:
jni/../../openssl/include/openssl/bio.h:679:27: warning: declaration of 'struct hostent' will not be visible outside of this
      function [-Wvisibility]
DEPRECATEDIN_1_1_0(struct hostent *BIO_gethostbyname(const char *name))
                          ^
jni/../../openssl/include/openssl/bio.h:680:1: error: expected function body after function declarator
DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
^
jni/../../openssl/include/openssl/bio.h:692:55: warning: declaration of 'union BIO_sock_info_u' will not be visible outside of
      this function [-Wvisibility]
                  enum BIO_sock_info_type type, union BIO_sock_info_u *info);
                                                      ^
In file included from jni/../../openssl/ssl/bio_ssl.c:16:
jni/../../openssl/include/openssl/err.h:247:1: error: expected function body after function declarator
DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:58:
In file included from jni/../../openssl/include/openssl/rsa.h:16:
In file included from jni/../../openssl/include/openssl/asn1.h:24:
jni/../../openssl/include/openssl/bn.h:291:1: error: expected function body after function declarator
DEPRECATEDIN_0_9_8(int
^
jni/../../openssl/include/openssl/bn.h:362:1: error: expected function body after function declarator
DEPRECATEDIN_0_9_8(int BN_get_params(int which)) /* 0, mul, 1 high, 2 low, 3
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:58:
In file included from jni/../../openssl/include/openssl/rsa.h:16:
jni/../../openssl/include/openssl/asn1.h:553:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
^
jni/../../openssl/include/openssl/asn1.h:553:68: error: expected ';' after top level declarator
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
                                                                   ^
                                                                   ;
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:58:
jni/../../openssl/include/openssl/rsa.h:206:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
^
jni/../../openssl/include/openssl/rsa.h:208:56: error: expected ';' after top level declarator
                                         void *cb_arg))
                                                       ^
                                                       ;
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:59:
In file included from jni/../../openssl/include/openssl/dsa.h:31:
jni/../../openssl/include/openssl/dh.h:118:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_0_9_8(DH *DH_generate_parameters(int prime_len, int generator,
^
jni/../../openssl/include/openssl/dh.h:118:1: error: conflicting types for 'DEPRECATEDIN_0_9_8'
jni/../../openssl/include/openssl/rsa.h:206:1: note: previous declaration is here
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:59:
In file included from jni/../../openssl/include/openssl/dsa.h:31:
jni/../../openssl/include/openssl/dh.h:121:61: error: expected ';' after top level declarator
                                              void *cb_arg))
                                                            ^
                                                            ;
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:59:
jni/../../openssl/include/openssl/dsa.h:122:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_0_9_8(DSA *DSA_generate_parameters(int bits,
^
jni/../../openssl/include/openssl/dsa.h:122:1: error: conflicting types for 'DEPRECATEDIN_0_9_8'
jni/../../openssl/include/openssl/rsa.h:206:1: note: previous declaration is here
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:59:
jni/../../openssl/include/openssl/dsa.h:129:63: error: expected ';' after top level declarator
                                                void *cb_arg))
                                                              ^
                                                              ;
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:61:
In file included from jni/../../openssl/include/openssl/ssl.h:50:
jni/../../openssl/include/openssl/x509.h:709:1: error: expected function body after function declarator
DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:61:
In file included from jni/../../openssl/include/openssl/ssl.h:56:
jni/../../openssl/include/openssl/hmac.h:28:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
^
jni/../../openssl/include/openssl/hmac.h:28:1: error: conflicting types for 'DEPRECATEDIN_1_1_0'
jni/../../openssl/include/openssl/asn1.h:553:1: note: previous declaration is here
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:61:
In file included from jni/../../openssl/include/openssl/ssl.h:56:
jni/../../openssl/include/openssl/hmac.h:29:40: error: expected ';' after top level declarator
                     const EVP_MD *md))
                                       ^
                                       ;
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:61:
jni/../../openssl/include/openssl/ssl.h:826:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEPRECATEDIN_1_1_0(void SSL_set_debug(SSL *s, int debug))
^
jni/../../openssl/include/openssl/ssl.h:826:1: error: conflicting types for 'DEPRECATEDIN_1_1_0'
jni/../../openssl/include/openssl/asn1.h:553:1: note: previous declaration is here
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:61:
jni/../../openssl/include/openssl/ssl.h:826:58: error: expected ';' after top level declarator
DEPRECATEDIN_1_1_0(void SSL_set_debug(SSL *s, int debug))
                                                         ^
                                                         ;
jni/../../openssl/include/openssl/ssl.h:1596:1: error: expected function body after function declarator
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_server_method(void)) /* SSLv3 */
^
jni/../../openssl/include/openssl/ssl.h:1611:1: error: expected function body after function declarator
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void)) /* TLSv1.0 */
^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:67:
jni/../../openssl/ssl/packet_locl.h:424:5: error: use of undeclared identifier 'OPENSSL_FILE'; did you mean 'OPENSSL_die'?
    OPENSSL_free(*data);
    ^
jni/../../openssl/include/openssl/crypto.h:137:27: note: expanded from macro 'OPENSSL_free'
        CRYPTO_free(addr, OPENSSL_FILE, OPENSSL_LINE)
                          ^
jni/../../openssl/include/openssl/crypto.h:324:20: note: 'OPENSSL_die' declared here
ossl_noreturn void OPENSSL_die(const char *assertion, const char *file, int line);
                   ^
In file included from jni/../../openssl/ssl/bio_ssl.c:17:
In file included from jni/../../openssl/ssl/ssl_locl.h:67:
jni/../../openssl/ssl/packet_locl.h:424:5: error: use of undeclared identifier 'OPENSSL_LINE'
    OPENSSL_free(*data);
    ^
jni/../../openssl/include/openssl/crypto.h:137:41: note: expanded from macro 'OPENSSL_free'
        CRYPTO_free(addr, OPENSSL_FILE, OPENSSL_LINE)
                                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: *** [obj/local/arm64-v8a/objs/ssl/__/__/openssl/ssl/bio_ssl.o] Error 1
Error building the libssl and libcrypto

**Comment by gustavogenovese** [comment]
you probably forgot to init the submodules, that's why you couldn't find openssl. Read the README.md
