### ISSUE TITLE
how to build libcurl without https(ssl)

### ISSUE THREAD

**Issue by ibaoger** [gcesarmza/curl-android-ios#37]
how to build libcurl without https(ssl)

**Comment by gustavogenovese** [comment]
Please review the bash scripts, all the information you need is there.
For Android, the script goes like this:
a) configure openssl for android
b) build openssl
c) configure curl with openssl (you'll see a `--with-ssl` line)
d) build curl

For iOS it's even simpler
a) configure curl with darwin ssl
b) build curl
