### ISSUE TITLE
zlib symbols are missing

### ISSUE THREAD

**Issue by skindhu** [gcesarmza/curl-android-ios#39]
when i add LOCAL_LDLIBS += -lz in Android.mk

then

Android NDK: WARNING:jni/Android.mk:curl: LOCAL_LDLIBS is always ignored for static libraries

**Comment by gustavogenovese** [comment]
Exactly, it's a static library, not dynamic. You have to add -lz to **your** library, check test Android project, which builds a dynamic library using this static lib, and it makes use of the -lz linker flag
