### ISSUE TITLE
License

### ISSUE THREAD

**Issue by darioxz** [gcesarmza/curl-android-ios#42]
Hi

This curl building script seems to do its job well and I'd like to use it in one of my projects. What is the license of this repository? Can I fork and use it for an open source project? Or can I just download the code without forking and integrate it into my solution? What about commercial use?

Thank you

Regards, Darioxz

**Comment by gustavogenovese** [comment]
Hey, As long as you don't violate cURL's and OpenSSL's license terms, you can use (copy, fork, etc) this project in your solution
Regards,

**Comment by darioxz** [comment]
Perfect, thank you very much.
