### ISSUE TITLE
Could you please post compiled Android binaries?

### ISSUE THREAD

**Issue by Rikk** [gcesarmza/curl-android-ios#53]
Thanks

**Comment by gustavogenovese** [comment]
Did you even read the README? "The goal of this project is to provide a pre-compiled version of libcurl to be used in Android and iOS." 
The binaries are in the repo, check the "prebuilt-with-ssl" folder

**Comment by Rikk** [comment]
It is being hard to find someone who has published updated binary (the `curl` command line program) for Android. The one in official page is very outdated and can't even run in Android 5+. The most updated I could find is v7.44.0.
Dunno how this "precompiled" 5MB file works, sorry, (I suppose it is either for in-app calls or for using during the final compilation itself?), but I see it is not ready for end-user usage.

**Comment by gustavogenovese** [comment]
This project is about libcurl a library to be used when you develop an app. It's not about building curl (executable) in order to run it on Android. I'm pretty sure though that you can adapt the build scripts and adjust them to build the curl executable
