### ISSUE TITLE
libcurl with BoringSSL

### ISSUE THREAD

**Issue by BlackHornet** [gcesarmza/curl-android-ios#9]
Hello, first of all:

Thank you very much for this repository, you are a gift for everybody who have to use libcurl in an android app.

Google announced to replace OpenSSL with its own fork BoringSSL in the future on Android. As this is already available via googlesource would it be possible that you can provide libcurl static builds with boringSSL support?

Afaik curl itself support compiled with BoringSSL since 7.44.0

**Comment by gustavogenovese** [comment]
Hi,
I took a look to the BoringSSL repository and the main problem I see is that it's not versioned. Currently this repo is pointing to a specific cURL version and a specific OpenSSL version, and I (try to) keep up with the updates to those repos. With BoringSSL this does not seem posible. I could though, point to a specific commit and build from there, but that doesn't look nice either. Even more, quoting their README.md file:
"Programs ship their own copies of BoringSSL when they use it and we update everything as needed when deciding to make API changes. This allows us to mostly avoid compromises in the name of compatibility. It works for us, but it may not work for you.".
So if you want to, you can go ahead and either fork this repo or submit a PR when you make it work with BoringSSL. 
On the other hand, Google has announced that libssl and libcrypto (probably with BoringSSL) will be a part of the NDK in a near future, so this whole repo might not even be useful anymore.
